-- =============================================================================
-- MUSIFY - CLEAN & GUARANTEED SUPABASE SETUP
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- =============================================================================

-- 1. SONGS TABLE
CREATE TABLE IF NOT EXISTS public.songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    artist_name TEXT NOT NULL,
    album_title TEXT DEFAULT 'Single',
    genre TEXT DEFAULT 'Tamil Hits',
    language TEXT DEFAULT 'Tamil',
    cover_url TEXT,
    audio_url TEXT NOT NULL,
    duration INTEGER DEFAULT 240,
    release_date TEXT,
    play_count BIGINT DEFAULT 0,
    lyrics TEXT,
    description TEXT,
    uploader_email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS on songs so anon and authenticated users can insert and select
ALTER TABLE public.songs DISABLE ROW LEVEL SECURITY;

-- 2. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supabase_uid UUID,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT DEFAULT 'USER',
    profile_image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable RLS on users so user accounts can be saved and queried freely
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

-- 3. ARTISTS TABLE
CREATE TABLE IF NOT EXISTS public.artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name TEXT NOT NULL,
    bio TEXT,
    profile_image TEXT,
    monthly_listeners BIGINT DEFAULT 0,
    verified BOOLEAN DEFAULT TRUE
);
ALTER TABLE public.artists DISABLE ROW LEVEL SECURITY;

-- 4. PLAYLISTS TABLE
CREATE TABLE IF NOT EXISTS public.playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    cover_url TEXT,
    created_by TEXT,
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.playlists DISABLE ROW LEVEL SECURITY;

-- 5. LIKED SONGS TABLE
CREATE TABLE IF NOT EXISTS public.liked_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    song_id BIGINT,
    liked_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.liked_songs DISABLE ROW LEVEL SECURITY;

-- 6. RECENTLY PLAYED TABLE
CREATE TABLE IF NOT EXISTS public.recently_played (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    song_id BIGINT,
    played_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.recently_played DISABLE ROW LEVEL SECURITY;

-- 7. STORAGE BUCKETS (Creates public buckets: music, covers, profiles)
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('music', 'music', true),
  ('covers', 'covers', true),
  ('profiles', 'profiles', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 8. STORAGE ACCESS POLICIES
DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Public Storage Select" ON storage.objects;
  DROP POLICY IF EXISTS "Public Storage Insert" ON storage.objects;
  DROP POLICY IF EXISTS "Public Storage Update" ON storage.objects;
  DROP POLICY IF EXISTS "Public Storage Delete" ON storage.objects;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

CREATE POLICY "Public Storage Select" ON storage.objects FOR SELECT USING (true);
CREATE POLICY "Public Storage Insert" ON storage.objects FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Storage Update" ON storage.objects FOR UPDATE USING (true);
CREATE POLICY "Public Storage Delete" ON storage.objects FOR DELETE USING (true);

